/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextPane;
import javax.swing.text.MutableAttributeSet;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;

/**
 *
 * @author Alexander Batista
 */
public class GUI extends javax.swing.JFrame {

    boolean integrar;
    String dato;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtxpFuncion = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jbtnIntegrando = new javax.swing.JButton();
        jbtnCuadrado = new javax.swing.JButton();
        jbtnCubo = new javax.swing.JButton();
        jbtnPotencia = new javax.swing.JButton();
        jbtnExponencial = new javax.swing.JButton();
        jbtnParentecisA = new javax.swing.JButton();
        jbtnParentecisC = new javax.swing.JButton();
        jbtnCosiente = new javax.swing.JButton();
        jbtnProducto = new javax.swing.JButton();
        jbtnDerivada = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CDI");
        setBackground(new java.awt.Color(102, 255, 204));
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Función:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        jtxpFuncion.setBorder(null);
        jtxpFuncion.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jtxpFuncion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxpFuncionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxpFuncionKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jtxpFuncion);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        jPanel3.setOpaque(false);

        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operadores:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        jPanel1.setOpaque(false);

        jbtnIntegrando.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtnIntegrando.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/integrando.png"))); // NOI18N
        jbtnIntegrando.setToolTipText("Integrando");
        jbtnIntegrando.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnIntegrando.setMaximumSize(new java.awt.Dimension(25, 25));
        jbtnIntegrando.setMinimumSize(new java.awt.Dimension(25, 25));
        jbtnIntegrando.setPreferredSize(new java.awt.Dimension(25, 25));
        jbtnIntegrando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIntegrandoActionPerformed(evt);
            }
        });

        jbtnCuadrado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtnCuadrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Cuadrado.png"))); // NOI18N
        jbtnCuadrado.setToolTipText("Potencia Cuadrado");
        jbtnCuadrado.setEnabled(false);
        jbtnCuadrado.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnCuadrado.setMaximumSize(new java.awt.Dimension(25, 25));
        jbtnCuadrado.setMinimumSize(new java.awt.Dimension(25, 25));
        jbtnCuadrado.setPreferredSize(new java.awt.Dimension(25, 25));
        jbtnCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCuadradoActionPerformed(evt);
            }
        });

        jbtnCubo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtnCubo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cubo.png"))); // NOI18N
        jbtnCubo.setToolTipText("Potencia Cubo");
        jbtnCubo.setEnabled(false);
        jbtnCubo.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnCubo.setMaximumSize(new java.awt.Dimension(25, 25));
        jbtnCubo.setMinimumSize(new java.awt.Dimension(25, 25));
        jbtnCubo.setPreferredSize(new java.awt.Dimension(25, 25));
        jbtnCubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCuboActionPerformed(evt);
            }
        });

        jbtnPotencia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtnPotencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/potencia.png"))); // NOI18N
        jbtnPotencia.setToolTipText("Potencia n");
        jbtnPotencia.setEnabled(false);
        jbtnPotencia.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnPotencia.setMaximumSize(new java.awt.Dimension(25, 25));
        jbtnPotencia.setMinimumSize(new java.awt.Dimension(25, 25));
        jbtnPotencia.setPreferredSize(new java.awt.Dimension(25, 25));
        jbtnPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPotenciaActionPerformed(evt);
            }
        });

        jbtnExponencial.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtnExponencial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/exponencial.png"))); // NOI18N
        jbtnExponencial.setToolTipText("Función Exponencial");
        jbtnExponencial.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnExponencial.setMaximumSize(new java.awt.Dimension(25, 25));
        jbtnExponencial.setMinimumSize(new java.awt.Dimension(25, 25));
        jbtnExponencial.setPreferredSize(new java.awt.Dimension(25, 25));
        jbtnExponencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExponencialActionPerformed(evt);
            }
        });

        jbtnParentecisA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtnParentecisA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ParentecisA.png"))); // NOI18N
        jbtnParentecisA.setToolTipText("Paréntecia Abierto");
        jbtnParentecisA.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnParentecisA.setMaximumSize(new java.awt.Dimension(25, 25));
        jbtnParentecisA.setMinimumSize(new java.awt.Dimension(25, 25));
        jbtnParentecisA.setPreferredSize(new java.awt.Dimension(25, 25));
        jbtnParentecisA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnParentecisAActionPerformed(evt);
            }
        });

        jbtnParentecisC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtnParentecisC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ParentecisC.png"))); // NOI18N
        jbtnParentecisC.setToolTipText("Paréntecia Cerrado");
        jbtnParentecisC.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnParentecisC.setMaximumSize(new java.awt.Dimension(25, 25));
        jbtnParentecisC.setMinimumSize(new java.awt.Dimension(25, 25));
        jbtnParentecisC.setPreferredSize(new java.awt.Dimension(25, 25));
        jbtnParentecisC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnParentecisCActionPerformed(evt);
            }
        });

        jbtnCosiente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtnCosiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Cosiente.png"))); // NOI18N
        jbtnCosiente.setToolTipText("Cosiente");
        jbtnCosiente.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnCosiente.setMaximumSize(new java.awt.Dimension(25, 25));
        jbtnCosiente.setMinimumSize(new java.awt.Dimension(25, 25));
        jbtnCosiente.setPreferredSize(new java.awt.Dimension(25, 25));
        jbtnCosiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCosienteActionPerformed(evt);
            }
        });

        jbtnProducto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtnProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/producto.png"))); // NOI18N
        jbtnProducto.setToolTipText("Producto");
        jbtnProducto.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnProducto.setMaximumSize(new java.awt.Dimension(25, 25));
        jbtnProducto.setMinimumSize(new java.awt.Dimension(25, 25));
        jbtnProducto.setPreferredSize(new java.awt.Dimension(25, 25));
        jbtnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnProductoActionPerformed(evt);
            }
        });

        jbtnDerivada.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtnDerivada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/integrando.png"))); // NOI18N
        jbtnDerivada.setToolTipText("Derivada");
        jbtnDerivada.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnDerivada.setMaximumSize(new java.awt.Dimension(25, 25));
        jbtnDerivada.setMinimumSize(new java.awt.Dimension(25, 25));
        jbtnDerivada.setPreferredSize(new java.awt.Dimension(25, 25));
        jbtnDerivada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDerivadaActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton11.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton11.setMaximumSize(new java.awt.Dimension(25, 25));
        jButton11.setMinimumSize(new java.awt.Dimension(25, 25));
        jButton11.setPreferredSize(new java.awt.Dimension(25, 25));

        jButton12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton12.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton12.setMaximumSize(new java.awt.Dimension(25, 25));
        jButton12.setMinimumSize(new java.awt.Dimension(25, 25));
        jButton12.setPreferredSize(new java.awt.Dimension(25, 25));

        jButton13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton13.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton13.setMaximumSize(new java.awt.Dimension(25, 25));
        jButton13.setMinimumSize(new java.awt.Dimension(25, 25));
        jButton13.setPreferredSize(new java.awt.Dimension(25, 25));

        jButton14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton14.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton14.setMaximumSize(new java.awt.Dimension(25, 25));
        jButton14.setMinimumSize(new java.awt.Dimension(25, 25));
        jButton14.setPreferredSize(new java.awt.Dimension(25, 25));

        jButton15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton15.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton15.setMaximumSize(new java.awt.Dimension(25, 25));
        jButton15.setMinimumSize(new java.awt.Dimension(25, 25));
        jButton15.setPreferredSize(new java.awt.Dimension(25, 25));

        jButton16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton16.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton16.setMaximumSize(new java.awt.Dimension(25, 25));
        jButton16.setMinimumSize(new java.awt.Dimension(25, 25));
        jButton16.setPreferredSize(new java.awt.Dimension(25, 25));

        jButton17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton17.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton17.setMaximumSize(new java.awt.Dimension(25, 25));
        jButton17.setMinimumSize(new java.awt.Dimension(25, 25));
        jButton17.setPreferredSize(new java.awt.Dimension(25, 25));

        jButton18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton18.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton18.setMaximumSize(new java.awt.Dimension(25, 25));
        jButton18.setMinimumSize(new java.awt.Dimension(25, 25));
        jButton18.setPreferredSize(new java.awt.Dimension(25, 25));

        jButton19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton19.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton19.setMaximumSize(new java.awt.Dimension(25, 25));
        jButton19.setMinimumSize(new java.awt.Dimension(25, 25));
        jButton19.setPreferredSize(new java.awt.Dimension(25, 25));

        jButton20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton20.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton20.setMaximumSize(new java.awt.Dimension(25, 25));
        jButton20.setMinimumSize(new java.awt.Dimension(25, 25));
        jButton20.setPreferredSize(new java.awt.Dimension(25, 25));

        jButton21.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton21.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton21.setMaximumSize(new java.awt.Dimension(25, 25));
        jButton21.setMinimumSize(new java.awt.Dimension(25, 25));
        jButton21.setPreferredSize(new java.awt.Dimension(25, 25));

        jButton22.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton22.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton22.setMaximumSize(new java.awt.Dimension(25, 25));
        jButton22.setMinimumSize(new java.awt.Dimension(25, 25));
        jButton22.setPreferredSize(new java.awt.Dimension(25, 25));

        jButton23.setBackground(new java.awt.Color(102, 255, 102));
        jButton23.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton23.setText("=");
        jButton23.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton23.setMaximumSize(new java.awt.Dimension(25, 25));
        jButton23.setMinimumSize(new java.awt.Dimension(25, 25));
        jButton23.setPreferredSize(new java.awt.Dimension(25, 25));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton24.setBackground(new java.awt.Color(255, 0, 0));
        jButton24.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton24.setText("N");
        jButton24.setToolTipText("Nuevo");
        jButton24.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton24.setMaximumSize(new java.awt.Dimension(25, 25));
        jButton24.setMinimumSize(new java.awt.Dimension(25, 25));
        jButton24.setPreferredSize(new java.awt.Dimension(25, 25));
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnIntegrando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnCubo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnExponencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnParentecisA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnParentecisC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnCosiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnDerivada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnIntegrando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnCubo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnExponencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnParentecisA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnParentecisC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnCosiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDerivada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(303, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(287, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnIntegrandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIntegrandoActionPerformed
        dato = JOptionPane.showInputDialog(this, "introduce el Diferencial (una letra)", "Diferencial: ", 2);
        this.jtxpFuncion.setText("∫()d".concat(String.valueOf(dato.charAt(0)).concat(" ")));
        integrar = true;
        this.jtxpFuncion.setCaretPosition(2);
        this.jtxpFuncion.grabFocus();
        this.jbtnDerivada.setEnabled(false);
        this.jbtnIntegrando.setEnabled(false);
    }//GEN-LAST:event_jbtnIntegrandoActionPerformed

    private void jbtnParentecisAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnParentecisAActionPerformed
        String sel = Select();
        this.jtxpFuncion.setText(sel.concat("(".concat(Select2())));
        this.jtxpFuncion.grabFocus();
        this.jtxpFuncion.setCaretPosition(sel.length() + 1);
    }//GEN-LAST:event_jbtnParentecisAActionPerformed

    private void jbtnParentecisCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnParentecisCActionPerformed
        String sel = Select();
        this.jtxpFuncion.setText(sel.concat(")".concat(Select2())));
        this.jtxpFuncion.grabFocus();
        this.jtxpFuncion.setCaretPosition(sel.length() + 1);
    }//GEN-LAST:event_jbtnParentecisCActionPerformed

    private void jbtnCosienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCosienteActionPerformed
        String sel = Select();
        this.jtxpFuncion.setText(sel.concat("()/()".concat(Select2())));
        this.jtxpFuncion.grabFocus();
        this.jtxpFuncion.setCaretPosition(sel.length() + 1);
    }//GEN-LAST:event_jbtnCosienteActionPerformed

    private void jbtnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnProductoActionPerformed
        String sel = Select();
        this.jtxpFuncion.setText(sel.concat("()()".concat(Select2())));
        this.jtxpFuncion.grabFocus();
        this.jtxpFuncion.setCaretPosition(sel.length() + 1);
    }//GEN-LAST:event_jbtnProductoActionPerformed

    private void jbtnCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCuadradoActionPerformed
        String sel = Select();
        this.jtxpFuncion.setText(sel.concat("^2".concat(Select2())));
        this.jtxpFuncion.grabFocus();
        this.jtxpFuncion.setCaretPosition(sel.length() + 2);
    }//GEN-LAST:event_jbtnCuadradoActionPerformed

    private void jbtnExponencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExponencialActionPerformed
        String sel = Select();
        this.jtxpFuncion.setText(sel.concat("e".concat(Select2())));
        this.jtxpFuncion.grabFocus();
        this.jtxpFuncion.setCaretPosition(sel.length() + 1);
    }//GEN-LAST:event_jbtnExponencialActionPerformed

    private void jbtnPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPotenciaActionPerformed
        String sel = Select();
        this.jtxpFuncion.setText(sel.concat("^".concat(Select2())));
        this.jtxpFuncion.grabFocus();
        this.jtxpFuncion.setCaretPosition(sel.length() + 1);
    }//GEN-LAST:event_jbtnPotenciaActionPerformed

    private void jbtnDerivadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDerivadaActionPerformed
        dato = JOptionPane.showInputDialog(this, "introduce el Diferencial (una letra)", "Diferencial: ", 2);
        this.jtxpFuncion.setText(this.jtxpFuncion.getText().concat(" d".concat(" \n──".concat("()\nd".concat(String.valueOf(dato.charAt(0)))))));
        integrar = false;
        changeLineSpacing(Float.valueOf("-0.5"), false, this.jtxpFuncion);
        this.jbtnIntegrando.setEnabled(false);
        this.jbtnDerivada.setEnabled(false);
        this.jtxpFuncion.grabFocus();
        this.jtxpFuncion.setCaretPosition(7);
    }//GEN-LAST:event_jbtnDerivadaActionPerformed

    private void jbtnCuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCuboActionPerformed
        String sel = Select();
        this.jtxpFuncion.setText(sel.concat("^3".concat(Select2())));
        this.jtxpFuncion.grabFocus();
        this.jtxpFuncion.setCaretPosition(sel.length() + 2);
    }//GEN-LAST:event_jbtnCuboActionPerformed

    private void jtxpFuncionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxpFuncionKeyPressed
        jtxasetFont(this.jtxpFuncion);
        int pos = 0;
        char caracter = evt.getKeyChar();
        if (this.jtxpFuncion.getText().equals("")) {
            this.jbtnDerivada.setEnabled(true);
            this.jbtnIntegrando.setEnabled(true);
        }
        if (Character.isLetter(caracter)) {
            if (!String.valueOf(evt.getKeyChar()).equals(dato)) {
                if (JOptionPane.showConfirmDialog(this, "Debe ingresar la misma letra del diferencial \n ¿Deséas Continuar?", "Información", 1) == 1) {

                    String cadena = this.jtxpFuncion.getText().substring(this.jtxpFuncion.getText().indexOf("(") + 1, this.jtxpFuncion.getText().lastIndexOf(")"));
                    for (int i = 0; i < cadena.length(); i++) {
                        if (Character.isLetter(cadena.charAt(i))) {
                            if (!String.valueOf(cadena.charAt(i)).equals(dato)) {
                                pos = i;
                                cadena = cadena.substring(0, i).concat(cadena.substring(i + 1, cadena.length()));
                            }
                        }
                    }
                    cadena = this.jtxpFuncion.getText().substring(0, this.jtxpFuncion.getText().indexOf("(") + 1).concat(cadena.concat(this.jtxpFuncion.getText().substring(this.jtxpFuncion.getText().indexOf(")"))));
                    this.jtxpFuncion.setText(cadena);
                    jtxasetFont(this.jtxpFuncion);
                    this.jtxpFuncion.grabFocus();

                    this.jtxpFuncion.setCaretPosition(pos + 7);
                }

            }
        } else {
            this.jbtnCuadrado.setEnabled(true);
            this.jbtnCubo.setEnabled(true);
            this.jbtnPotencia.setEnabled(true);
        }

    }//GEN-LAST:event_jtxpFuncionKeyPressed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        this.jtxpFuncion.setText("");
        this.jbtnDerivada.setEnabled(true);
        this.jbtnIntegrando.setEnabled(true);
        this.jTextPane1.setText("");
        integrar = false;
        this.jtxpFuncion.grabFocus();
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jtxpFuncionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxpFuncionKeyReleased

    }//GEN-LAST:event_jtxpFuncionKeyReleased

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        String op, cad;
        ArrayList resultados = new ArrayList();
        if (!integrar) {
            op = "D";
        } else {
            op = "I";
        }
        cad = this.jtxpFuncion.getText().substring(this.jtxpFuncion.getText().indexOf("(") + 1, this.jtxpFuncion.getText().lastIndexOf(")"));
        if (!"".equals(cad)) {
            resultados = CDI.CDIMaster(cad, op, dato);
        } else if (integrar) {
            System.out.println(dato);
            resultados = CDI.CDIMaster("1", op, dato);
        } else {
            JOptionPane.showMessageDialog(this, "Para derivar debe colocar al menos un numero diferente de 0", "Error", JOptionPane.ERROR_MESSAGE);
            this.jtxpFuncion.grabFocus();
            if (!integrar) {
                this.jtxpFuncion.setCaretPosition(7);
            }
        }
        for (Object resultado : resultados) {
            this.jTextPane1.setText(this.jTextPane1.getText().concat(resultado.toString()));
            changeLineSpacing(Float.valueOf("1"), false, this.jTextPane1);
        }
        resultados.clear();
    }//GEN-LAST:event_jButton23ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton jbtnCosiente;
    private javax.swing.JButton jbtnCuadrado;
    private javax.swing.JButton jbtnCubo;
    private javax.swing.JButton jbtnDerivada;
    private javax.swing.JButton jbtnExponencial;
    private javax.swing.JButton jbtnIntegrando;
    private javax.swing.JButton jbtnParentecisA;
    private javax.swing.JButton jbtnParentecisC;
    private javax.swing.JButton jbtnPotencia;
    private javax.swing.JButton jbtnProducto;
    private javax.swing.JTextPane jtxpFuncion;
    // End of variables declaration//GEN-END:variables

    private String Select() {
        return this.jtxpFuncion.getText().substring(0, this.jtxpFuncion.getCaretPosition());
    }

    private String Select2() {
        return this.jtxpFuncion.getText().substring(this.jtxpFuncion.getCaretPosition(), this.jtxpFuncion.getText().length());
    }

    private void changeLineSpacing(float factor, boolean replace, JTextPane jtxpvariable) {
        jtxpvariable.selectAll();
        MutableAttributeSet set = new SimpleAttributeSet(jtxpvariable.getParagraphAttributes());
        StyleConstants.setLineSpacing(set, factor);
        jtxpvariable.setParagraphAttributes(set, replace);
        jtxasetFont(jtxpvariable);
    }

    private void jtxasetFont(JTextPane jtxpvariable) {
        Font fuente = new Font("Times New Roman", Font.ITALIC, 18);
        jtxpvariable.setFont(fuente);
    }

    private String crearCadena(String cad) {
        if (cad.indexOf(")(") == 1) {
            cad = "(".concat(cad).concat(")");
        }
        System.out.println(cad + "   yo");
        return cad;
    }

}
